"""add weekly report fields

Revision ID: 036b4ccef802
Revises: ba6237986c86
Create Date: 2026-09-16 15:36:02.509384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '036b4ccef802'
down_revision: Union[str, None] = 'ba6237986c86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_projects', sa.Column('report_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('monitor_projects', sa.Column('report_opt_out', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_projects', 'report_opt_out')
    op.drop_column('monitor_projects', 'report_sent_at')
    # ### end Alembic commands ###
