"""add competitor mentions

Revision ID: 164211f86fd5
Revises: c34888f2455b
Create Date: 2026-09-09 00:09:39.512872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164211f86fd5'
down_revision: Union[str, None] = 'c34888f2455b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitor_mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name_raw', sa.String(length=200), nullable=False),
    sa.Column('name_key', sa.String(length=200), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['monitor_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_mentions_name_key'), 'monitor_mentions', ['name_key'], unique=False)
    op.create_index(op.f('ix_monitor_mentions_run_id'), 'monitor_mentions', ['run_id'], unique=False)
    op.add_column('monitor_runs', sa.Column('response_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_runs', 'response_text')
    op.drop_index(op.f('ix_monitor_mentions_run_id'), table_name='monitor_mentions')
    op.drop_index(op.f('ix_monitor_mentions_name_key'), table_name='monitor_mentions')
    op.drop_table('monitor_mentions')
    # ### end Alembic commands ###
