"""record failed monitor runs

Revision ID: ba6237986c86
Revises: 4d5d35b7e3bc
Create Date: 2026-09-16 14:24:23.414889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba6237986c86'
down_revision: Union[str, None] = '4d5d35b7e3bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_runs', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_runs', 'error')
    # ### end Alembic commands ###
