"""init

Revision ID: c2730588f273
Revises: 
Create Date: 2026-06-30 00:26:04.283402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2730588f273'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('share_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('place_name', sa.String(length=200), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_reports_share_id'), 'audit_reports', ['share_id'], unique=True)
    op.create_table('monitor_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('owner_email', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['monitor_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('ai_model', sa.String(length=50), nullable=False),
    sa.Column('mentioned', sa.Boolean(), nullable=False),
    sa.Column('response_snippet', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('ran_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['monitor_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitor_runs_ran_at'), 'monitor_runs', ['ran_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitor_runs_ran_at'), table_name='monitor_runs')
    op.drop_table('monitor_runs')
    op.drop_table('monitor_questions')
    op.drop_table('monitor_projects')
    op.drop_index(op.f('ix_audit_reports_share_id'), table_name='audit_reports')
    op.drop_table('audit_reports')
    # ### end Alembic commands ###
