"""add brand_keyword

Revision ID: c34888f2455b
Revises: c2730588f273
Create Date: 2026-06-30 00:29:48.713819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c34888f2455b'
down_revision: Union[str, None] = 'c2730588f273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitor_projects', sa.Column('brand_keyword', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monitor_projects', 'brand_keyword')
    # ### end Alembic commands ###
